### ISSUE TITLE
Unknown Subtype: {E2A2EEF0-14BE-4BFE-B65C-5669125F62A7}

### ISSUE THREAD

**Issue by Sopholos** [dotnet-architecture/MNISTTensorCNTK#2]
When I trying to open project in VS I receive next error:

> The project file 'D:\tmp\MNISTTensorCNTK-master\MNISTTensorCNTK-master\Training\Training.pyproj' cannot be opened.
> 
> There is a missing project subtype.
> Subtype: '{E2A2EEF0-14BE-4BFE-B65C-5669125F62A7}' is unsupported by this installation.
> 

I installed all stuff related Python but still same.
Even trying to remove this guid from types in Training.pyproj but looks like VS automatically adds it back, because of error still same

**Comment by Sopholos** [comment]
Changed to 

`<ProjectTypeGuids>{a41c8ea1-112a-4a2d-9f91-29557995525f};{888888a0-9f3d-457c-b088-3a5042f75d52}</ProjectTypeGuids>`

and problem gone.

**Comment by sskset** [comment]
@Sopholos  Thanks, you solved my problem too.

**Comment by tymokvo** [comment]
Worked for me as well. Thanks!
